"""Prospect briefs — generated from accountbriefbot dashboard + Claude.

Regenerate by running scripts/regen_fixtures.py from the project root.
"""

PROSPECTS = {   'anthropic': {   'name': 'Anthropic',
                     'employees': '5323',
                     'headcount_growth_yoy': '',
                     'stage': 'Series G ($380B)',
                     'hq': 'San Francisco, California',
                     'summary': 'AI safety & foundation models. Pure Mac fleet, Jamf MDM.',
                     'talking_points': [   '5300+ employees, all-Mac environment + Jamf MDM',
                                           'Series G funded 2025 at $380B valuation',
                                           'Hybrid work model, Google Workspace ecosystem',
                                           'Tier 1 AI/ML vertical—high hardware refresh cycle',
                                           'Strong investor backing (Google, Amazon, Lightspeed)'],
                     'contacts': [{'name': 'John Fazzolari', 'title': 'Account Owner', 'email': ''}]},
    'applied intuition': {   'name': 'Applied Intuition',
                             'employees': '3844',
                             'headcount_growth_yoy': '',
                             'stage': 'private',
                             'hq': 'Mountain View, California',
                             'summary': 'Fleet unknown — Mac likely (inferred 23/25)',
                             'talking_points': ['Work Model: office-first'],
                             'contacts': []},
    'stripe': {   'name': 'Stripe',
                  'employees': '14632',
                  'headcount_growth_yoy': '',
                  'stage': 'Private ($159B)',
                  'hq': 'San Francisco, CA',
                  'summary': 'Payments infrastructure for millions of businesses globally',
                  'talking_points': [   '14.6K employees, 2022 layoff signal',
                                        'Financial services, not hardware-focused',
                                        'Payment processing, VAT automation platform',
                                        'Series I secondary liquidity round',
                                        'Not aligned with Revivn use case'],
                  'contacts': []},
    'notion': {   'name': 'Notion',
                  'employees': '800',
                  'headcount_growth_yoy': '',
                  'stage': 'Private ($10B+)',
                  'hq': 'San Francisco, CA',
                  'summary': 'All-in-one workspace: docs, notes, wikis, databases, task mgmt.',
                  'talking_points': [   '100M+ users; 4M paying customers; 50% Fortune 500 adoption',
                                        'Unified productivity suite replaces multiple point tools',
                                        'Customizable workflows reduce legacy software sprawl',
                                        'High employee retention in competitive talent market',
                                        'Cloud-native platform simplifies asset lifecycle tracking'],
                  'contacts': []},
    'figma': {   'name': 'Figma',
                 'employees': '2774',
                 'headcount_growth_yoy': '+3%',
                 'stage': 'Public',
                 'hq': 'San Francisco, CA',
                 'summary': 'Cloud-based collaborative design platform for prototyping & product development',
                 'talking_points': [   'Design teams → hardware refresh cycles tied to creative workflows',
                                       '2774 employees across SF, NYC hubs generating used device volume',
                                       'Modest +3% YoY growth signals stable, mature headcount',
                                       'ChatGPT integration & FigJam expansion driving tool consolidation'],
                 'contacts': []},
    'vercel': {   'name': 'Vercel',
                  'employees': '897',
                  'headcount_growth_yoy': '',
                  'stage': 'Series F ($9.3B)',
                  'hq': 'Covina, California',
                  'summary': 'Frontend cloud platform for modern web apps.',
                  'talking_points': [   '897 devs likely using Macs + company hardware',
                                        'Series F 2025 — scaling eng infrastructure',
                                        'Remote-friendly model increases device refresh',
                                        'DevTools: high churn on laptops/peripherals',
                                        'Recent breach signals security audit cycle'],
                  'contacts': []},
    'ramp': {   'name': 'Ramp',
                'employees': '2093',
                'headcount_growth_yoy': '',
                'stage': 'Series E ($32B)',
                'hq': 'New York City, NY',
                'summary': 'All-in-one financial ops platform: corporate cards, expense mgmt, bill pay.',
                'talking_points': [   'Unified spend platform reduces manual data entry + coding',
                                      '50K+ teams use Ramp; strong enterprise adoption signals',
                                      '4 funding rounds in 2025; rapid scaling momentum',
                                      'AI-powered automation cuts month-end close time',
                                      'Corporate card controls + approval workflows = fleet governance'],
                'contacts': []}}
